# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\danii\Downloads\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(431, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(main)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.draw_circle = QtWidgets.QPushButton(main)
        self.draw_circle.setObjectName("draw_circle")
        self.verticalLayout.addWidget(self.draw_circle)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.draw_circle.setText(_translate("main", "draw"))
